### ISSUE TITLE
GetSpecificEventEntriesCount

### ISSUE THREAD

**Issue by VladKRP** [VladKRP/Courses#10]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L301-L304
В чем может быть дело, почему не работает?
Насчитывает на 20 событий меньше чем ожидается.

**Comment by aorgish** [comment]
Тут надо разобраться кто виноват

**Comment by VladKRP** [comment]
На лэптопе у меня этот тест не проходит, а в лабе все работает
