### ISSUE TITLE
Tokenize

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#13]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/03-Collections/Collections/Collections.cs#L66-L67
Вместо этого блока проще `readedText = reader.ReadToEnd();`
Но в любом случае читать весь файл сразу в память неправильно. Если файл будет в несколько гигабайт, то просто может не хватить памяти. В этом методе памяти надо в 2 раза больше, чем размер файла.
Поэтому надо читать построчно и возвращать строки через yield return. Это будет работать гораздо быстрее и занимать памяти максимум в размер самой большой строки. В этом и есть суть yield return.

**Comment by VladKRP** [comment]
Пробовал сначала полностью считывать, но там в тестах метод ReadToEnd переопределен и выкидывает исключение.
Даже не думал что yield и в таких случаях используется.
Исправил с использование yield return.
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/03-Collections/Collections/Collections.cs#L59
