### ISSUE TITLE
GetPrefixItems

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#15]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L93
Пра сравнении строк без учета регистра лучше пользовать специальными методами, а не приводить строки к одному регистру. Методы ToLower() и ToUpper() создают в памяти дополнительные строки, которые потом еще нужно убирать сборщику мусора. Очень часто это влияет на общую производительность. 

Тоже самое тут:
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L213
Больше я не буду указывать эту ошибку, надо самому найти все места и исправить

**Comment by VladKRP** [comment]
Исправил, но не знаю будет ли это самым эффективным вариантом.
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L91
