### ISSUE TITLE
PropagateItemsByPositionIndex<T>

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#16]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L123-L129
Все методы в этом задании - на использование LINQ и методов Enumerable. После прохождения этого задания нужно забыть про паттерн 
```
List<T> items = new List<T>();
...
items.Add(...);
...
return items;
```
Такой код показывает явный непрофессионализм. Вместо него - либо yield return либо LINQ-методы.

Аналогично тут: https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L243-L250
Больше не буду указывать на такой тип ошибки, надо найти все и исправить

**Comment by VladKRP** [comment]
Воспользовался yield return 
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L503

**Comment by VladKRP** [comment]
Не представляю пока другого решения
