### ISSUE TITLE
GetStringOfSequence<T>

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#17]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L164-L167
Забыл про string.Join или предыдущие задания не сам делал?

**Comment by VladKRP** [comment]
Да, что-то вообще про join не подумал.
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L161
