### ISSUE TITLE
GetCountOfGreaterThen10

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#18]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L198
Можно сделать с помощью одного `Count(...)`

**Comment by VladKRP** [comment]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L194
