### ISSUE TITLE
GetCountOfStringsWithLengthEqualsTo3

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#19]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L228
Можно использовать более простой и быстрый способ, чем `GroupBy`

**Comment by VladKRP** [comment]
Distinct?
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L224
