### ISSUE TITLE
GetDigitCharsCount

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#20]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L296
Тут тоже можно одним `Count` обойтись. `Select(x=>x)` как-то не имеет большого смысла

**Comment by VladKRP** [comment]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L282
