### ISSUE TITLE
SortStringsByLengthAndAlphabet

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#22]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L360
Странно, что это прошло через тесты, надо будет как-то контр-тест против такого написать :)
Второй вызов OrderBy может испортить порядок, который был сформирован первым OrderBy. Есть специальный метод, чтобы добавить второй критерий в сортировку. Или пользоваться только одним OrderBy со сложным условием

**Comment by VladKRP** [comment]
Писал достаточно давно и из-за того что тест проходил забыл поправить.
Вторым вызовом должен быть ThenBy, да и параметры тогда местами меняются.
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L345
Сортировал по параметрам наоборот, сначала в алфавитном порядке, а потом отсортированные в алфавитном по длине.
