### ISSUE TITLE
GetMissingDigits

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#23]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L374
Во первых, string - это уже IEnumerable<char>, поэтому эту строку можно написать просто как 
```
var missingDigits = "0123456789";
```

Во вторых, `string.Concat(data)` - это очень неудачное решение, потому что опять же все миллион элементов будут сцепливаться в одну гигантскую строку.

**Comment by VladKRP** [comment]
Поправил
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L359
