### ISSUE TITLE
GetStringsOnly

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#24]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L469
`GetType` и привдение типов - это очень плохой подход, практически никогда не надо им пользоваться. Есть простой linq-метод, который умеет решать эту задачу

**Comment by VladKRP** [comment]
Что насчет такого подхода?
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L454
