### ISSUE TITLE
IsSequenceHasNulls

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#25]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L502
Паттерты типа этого или типа такого
```
if (condition)
   return true;
else
  return false;
```
очень просто записываются в виде:
```
return (condition);
```

**Comment by VladKRP** [comment]
Исправил
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L488
