### ISSUE TITLE
IsAllStringsAreUppercase

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#26]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L517-L520
Про Concat я уже писал, больше не буду. Найти все Concat, если еще есть и исправить

**Comment by VladKRP** [comment]
Тут возникла небольшая проблемка, используя SelectMany при проверке пустого символа isUpper возвращает true.
Я выделил отдельную часть, где происходит проверка на то, пуста ли строка, т.к проверки на пустой символ нет.
Может есть более эффективный вариант?
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L503

Избавился от всех Concat в методах
