### ISSUE TITLE
AreNumericListsEqual

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#27]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L557
Про такой подход уже писал выше, больше не буду. Найти все такое ошибки и исправить, и больше так не делать.

**Comment by VladKRP** [comment]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L503
