### ISSUE TITLE
GetAllPairs

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#28]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L637-L640
Неожиданно, это обычно бывает, когда ответ искать на stackoverflow, а не в документации. 
Query syntax уже давно никто не использует, все давно поняли, что method syntax намного проще и понятнее. Надо написать с помощью нормальных методов.

**Comment by VladKRP** [comment]
Не знал как сделать махинации такого типа с помощью method syntax, поэтому и воспользовался query syntax. Решение с использованием query syntax показалось проще.
Вот переделанное
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/04-Enumerable/Enumerable/Task.cs#L503
