### ISSUE TITLE
ConvertToList<T>

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#3]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/02-Generics/Generics/Generics.cs#L51
Выражение `(T)System.ComponentModel.TypeDescriptor.GetConverter(typeof(T))` вычисляется каждый раз внутри цикла, лучше вычислить его один раз. Все инварианты всегда лучше выносить за цикл.

**Comment by VladKRP** [comment]
Поправил
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/02-Generics/Generics/Generics.cs#L51-L52
