### ISSUE TITLE
SwapArrayElements<T>

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#4]
А если удалить эти строки, то будет ли все работать как надо:
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/02-Generics/Generics/Generics.cs#L67-L68

**Comment by VladKRP** [comment]
Да, все работает.
Данное исключение по умолчанию выкидывается, при попытке доступа к элементу не входящему в границы массива.
Так что, это проверка пожалуй лишняя
