### ISSUE TITLE
TimeoutSafeInvoke<T>

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#6]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/02-Generics/Generics/Generics.cs#L176
Что за магическая цифра 3 ? Обычно вместо магических цифр объявляют константы с понятным именем.

**Comment by VladKRP** [comment]
Добавил константу
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/02-Generics/Generics/Generics.cs#L175,#L177
