### ISSUE TITLE
GetOrBuildValue<TKey, TValue>

### ISSUE THREAD

**Issue by aorgish** [VladKRP/Courses#8]
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/03-Collections/Collections/Collections.cs#L231-L232
Тут 2 раза выполняется поиск - сначала ищем есть ли ключ, потом повторно по ключу ищем значение. Надо за один раз все делать.

https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/03-Collections/Collections/Collections.cs#L235
Можно не вызывать Invoke, а просто `entity = builder()`

**Comment by VladKRP** [comment]
Поправил
https://github.com/VladKRP/Courses/blob/master/Net-training-tasks/03-Collections/Collections/Collections.cs/#L225-#L230
